# Generated by Django 6.0.5 on 2026-05-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_answer_confidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('HR', 'HR'), ('Technical', 'Technical'), ('Coding', 'Coding')], max_length=20)),
                ('question', models.TextField()),
            ],
        ),
    ]
